language: node_js
cache:
  directories:
    - $HOME/.npm
notifications:
  email: false
node_js:
  - 8
before_script:
  - npm prune
after_success:
  - npm run semantic-release
branches:
  except:
    - /^v\d+\.\d+\.\d+$/
deploy:
  provider: script
  script: DEBUG=glitch-deploy* npx glitch-deploy
  on:
    branch: master
